# Generated by Django 2.2 on 2019-04-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crim', models.IntegerField()),
                ('zn', models.IntegerField()),
                ('indus', models.IntegerField()),
                ('chas', models.IntegerField()),
                ('nox', models.IntegerField()),
                ('rm', models.IntegerField()),
                ('age', models.IntegerField()),
                ('dis', models.IntegerField()),
                ('rad', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('ptratio', models.IntegerField()),
                ('bk', models.IntegerField()),
                ('lstat', models.IntegerField()),
            ],
        ),
    ]
